scalar Date

type User {
  id: ID!
  rfid: String!
  name: String!
}

input UserQuery {
  id: ID
  rfid: String
  name: String
}

type Tracker {
  id: ID!
  rfid: String!
  channel: String!
}

input TrackerQuery {
  id: ID
  rfid: String
  channel: String
}

type Coordinate {
  x: Float!
  y: Float!
}

type SportRecord {
  id: ID!
  user: User!
  tracker: Tracker!
  startTime: Date!
  endTime: Date
  path: [Coordinate]!
}

input SportRecordQuery {
  id: ID
  user: UserQuery
  tracker: TrackerQuery
  startTime: Date
  endTime: Date
}

interface ResourceType {
  id: ID!
  name: String!
}

input ResourceTypeQuery {
  id: ID
  name: String
}

type SpaceType implements ResourceType {
  id: ID!
  name: String!
}

type EquipmentType implements ResourceType {
  id: ID!
  name: String!
}

type Time {
  hour: Int!
  minute: Int!
}

type Duration {
  start: Time!
  end: Time!
}

interface Resource {
  id: ID!
  name: String!
  type: ResourceType!
  isAvaliable: Boolean!
  avaliableDuration: Duration!
  createAt: Date!
}

input ResourceQuery {
  id: ID
  name: String
  type: ResourceTypeQuery
  isAvaliable: Boolean
  createAt: Date
}

type Space implements Resource {
  id: ID!
  name: String!
  type: ResourceType!
  isAvaliable: Boolean!
  avaliableDuration: Duration!
  createAt: Date!
}

type Equipment implements Resource {
  id: ID!
  name: String!
  type: ResourceType!
  isAvaliable: Boolean!
  avaliableDuration: Duration!
  createAt: Date!
}

type Reservation {
  id: ID!
  startTime: Date!
  endTime: Date!
  isActived: Boolean!
  isClosed: Boolean!
  user: User!
  resource: Resource!
}

input ReservationQuery {
  id: ID
  startTime: Date
  endTime: Date
  isActived: Boolean
  isClosed: Boolean
  user: UserQuery
  resource: ResourceQuery
}

type Query {
  users(query: UserQuery): [User]
  trackers(query: TrackerQuery): [Tracker]
  sportRecords(query: SportRecordQuery): [SportRecord]
  spaceTypes(query: ResourceTypeQuery): [SpaceType]
  equipmentTypes(query: ResourceTypeQuery): [EquipmentType]
  spaces(query: ResourceQuery): [Space]
  equipments(query: ResourceQuery): [Equipment]
  reservations(query: ReservationQuery): [Reservation]
}
